name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    # https://github.com/marketplace/actions/git-semantic-version?version=v5.3.0
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v5.3.0
      with: 
        major_pattern: "major:"
        minor_pattern: "feat:"
        version_format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version_image
    
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        NEW_VERSION: ${{ steps.version_image.outputs }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "NEW_VERSION: $NEW_VERSION !!!!!!!!!!!"
    
    # - name: Build docker image
    #   run: |
    #     docker build -t guerrerovicttor/docker-graphql:0.0.2 .
    #     docker build -t guerrerovicttor/docker-graphql:latest .

    # - name: Push docker image
    #   run: |
    #     docker push guerrerovicttor/docker-graphql:0.0.2
    #     docker push guerrerovicttor/docker-graphql:latest
